# -*- coding: utf-8 -*-

"""\
ExaWind Python Library
======================

Utilities for interacting with computational solvers used in the ExaWind
framework (https://github.com/exawind/)

"""

import os
import subprocess
from pathlib import Path
from datetime import datetime
from setuptools import setup

VERSION = "0.0.1"
basedir = Path(__file__).parent.resolve()

# https://github.com/numpy/numpy/blob/master/setup.py
def git_revision():
    """Return the Git SHA-ID if available"""
    def _minimal_ext_cmd(cmd):
        # construct minimal environment
        env = {}
        for k in ['SYSTEMROOT', 'PATH']:
            v = os.environ.get(k)
            if v is not None:
                env[k] = v
        # LANGUAGE is used on win32
        env['LANGUAGE'] = 'C'
        env['LANG'] = 'C'
        env['LC_ALL'] = 'C'
        out = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                               env=env).communicate()[0]
        return out

    try:
        out = _minimal_ext_cmd(['git', 'rev-parse', 'HEAD'])
        git_sha_id = out.strip().decode('ascii')
    except OSError:
        git_sha_id = "unknown"

    return git_sha_id

def write_version(fname="exawind/version.py"):
    ver_text = """# -*- coding: utf-8 -*-
#
# DO NOT EDIT!
# This file is automatically generated by setup
# Timestamp: %(timestamp)s+00.00
#

version = '%(version)s'
full_version = '%(full_version)s'
git_revision = '%(git_revision)s'
    """
    git_rev = git_revision()
    full_version = (VERSION + "-g" + git_rev[:7]
                    if git_rev != "unknown"
                    else VERSION)
    with open(fname, 'w') as fh:
        fh.write(
            ver_text % dict(
                version=VERSION,
                full_version=full_version,
                git_revision=git_rev,
                timestamp=datetime.utcnow().isoformat()))

write_version()

classifiers = [
    "Development Status :: 3 -Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Physics"
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Utilities",
]

setup(
    name="exawind",
    version=VERSION,
    url="https://github.com/sayerhs/py-exawind",
    license="Apache License, Version 2.0",
    description="Exawind Python Library",
    long_description=__doc__,
    author="Shreyas Ananthan",
    maintainer="Shreyas Ananthan",
    platforms="any",
    classifiers=classifiers,
    include_package_data=True,
    packages=[
        'exawind'
    ],
)
